
export const COMENZAR_DERCARGA_SPOTIFY = 'COMENZAR_DERCARGA_SPOTIFY';
export const COMENZAR_DERCARGA_SPOTIFY_EXITO = 'COMENZAR_DERCARGA_SPOTIFY_EXITO';
export const COMENZAR_DERCARGA_SPOTIFY_ERROR = 'COMENZAR_DERCARGA_SPOTIFY_ERROR';

export const DESCARGA_SPOTIFY_EXITO = 'DESCARGA_SPOTIFY_EXITO';
export const DESCARGA_SPOTIFY_ERROR = 'DESCARGA_SPOTIFY_ERROR';

export const ACTUALIZAR_INPUT_BUSQUEDA = 'ACTUALIZAR_INPUT_BUSQUEDA';
export const ACTUALIZAR_NUM_PAGE = 'ACTUALIZAR_NUM_PAGE';

export const ACTUALIZAR_SHOW_LIST_SONG = 'ACTUALIZAR_SHOW_LIST_SONG';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

